config/routes.rb
Rails.application.routes.draw do
 
  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  
  resources :admin_users, :except => [:show] do 
    member do
      get :delete
    end
  end
  
  resources :subjects do [:new]
    member do
      get :delete
    end
  end
  
  resources :pages do [:new]
    member do
      get :delete
    end
  end
  
  resources :sections do [:new]
    member do
      get :delete
    end
  end
  
  get 'portfolio/index'
  get 'portfolio/show'
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/niyi'
  get 'demo/escape_output'
  #default route might be deprecated
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
    
    #self.table_name = "admin_users"
    
    has_secure_password
    
    has_and_belongs_to_many :pages
    has_many :section_edits, :class_name => 'SectionEdit'
    has_many :sections, :through => :section_edits
    
   # attr_accessor :name
    
    EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9._]+\.[a-z]{2,4}\Z/i
    FORBIDDEN_USERNAMES = ['littlebopeep','humptydumpty','marymary']
    
    #validates_length_of :email, :maximum => 100
    #validates_format_of :email, :with => EMAIL_REGEX
    #validates_confirmation_of :email
    
    
    # sexy validations
    validates :first_name, :presence => true,
                            :length => {:maximum => 25 }
    validates :last_name, presence: true,
                            length: { maximum: 50 }
    validates :username, length: { within: 8..25 },
                        uniqueness: true
    validates :email, presence: true,
                    length: { maximum: 100 },
                    format: EMAIL_REGEX,
                    confirmation: true
                    
    validate :username_is_allowed
    validate :no_new_users_on_thursday, :on => :create
    
    scope :sorted, lambda { order('last_name ASC, first_name ASC') }
    
    def name
        "#{first_name} #{last_name}"
    end
    
    
    private
    
    def username_is_allowed
        if FORBIDDEN_USERNAMES.include?(username)
            errors.add(:username, "has been restricted from use.")
        end
    end
    
    def no_new_users_on_thursday
        if Time.now.wday == 5
            errors.add(:base, "No new users on Thursdays.")
        end
    end
    
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  
  layout 'admin'
  
  before_action :confirm_logged_in
  before_action :require_admin, :except => [:index, :new, :create]
  before_action :fetch_all_admins, :only => [:index]
  
  
  def index
    fetch_all_admins
  end

  def new
    @admin = AdminUser.new
  end

  def create
    @admin = AdminUser.new(admin_user_params)
    if @admin.save
      flash[:notice] = "Admin user successfully saved"
      redirect_to(admin_users_path)
    else
      flash.now[:notice] = "Something went worng, admin user was not saved"
      render 'new'
    end
  end

  def edit
    require_admin
  end

  def update
    require_admin
    if @admin.update_attributes(admin_user_params)
      flash[:notice] = "Admin user upadted successfully."
      redirect_to(admin_users_path)
    else
      flash[:notice] = "Something went wrong, admin user did not update."
      render 'edit'
    end
  end

  def delete
    require_admin
  end

  def destroy
    require_admin
    @admin.destroy
    flash[:notice] = "Admin user deleted successfully."
    redirect_to(admin_users_path)
  end
  
  private
  
  def admin_user_params
    params.require(:admin_user).permit(
      :first_name,
      :last_name,
      :email,
      :username,
      :password)
  end
  
  def fetch_all_admins
    @admin_list = AdminUser.sorted
  end
  
  def require_admin
    @admin = AdminUser.find(params[:id])
  end
  
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
    <tr>
        <th><%= f.label(:first_name) %></th>
        <td><%= f.text_field(:first_name) %></td>
    </tr>
    <tr>
        <th><%= f.label(:last_name) %></th>
        <td><%= f.text_field(:last_name) %></td>
    </tr>
    <tr>
        <th><%= f.label(:email) %></th>
        <td><%= f.text_field(:email) %></td>
    </tr>
    <tr>
        <th><%= f.label(:username) %></th>
        <td><%= f.text_field(:username) %></td>
    </tr>
    <tr>
        <th><%= f.label(:password) %></th>
        <td><%= f.password_field(:password) %></td>
    </tr>
</table>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete Admin User" %>

<%= link_to("<< Back to Admin List", admin_users_path, :class => 'back-link') %>

    <div class="subject delete">
        <h2>Delete Admin User</h2>
        
        <%= form_for(@admin, :method => 'delete') do |f| %>
            <p>Are you sure you want to permanently delete this admin user?</p>
            
            <p class="reference-name"><%= f.object.name %></p>
            
            <div class="form-buttons">
                <%= f.submit("Delete Admin User") %>
            </div>
        <% end %>
    </div>

app/views/admin_users/edit.html.erb
<% @page_title = "Edit Admin User" %>

<%= link_to("<< Back to Admin List", admin_users_path, :class => 'back-link') %>

    <div class="subject edit">
        <h2>Edit Admin User</h2>
        
        <%= form_for @admin do |f| %>
            
            <%= render(:partial => 'form', :locals => {:f => f}) %>
            
            <div class="form-buttons">
                <%= f.submit("Update Admin User") %>
            </div>
        <% end %>
    </div>

app/views/admin_users/index.html.erb
<% @page_title = "Admin Users List" %>

<%= link_to("<< Back to Menu", access_menu_path, :class => 'action new') %>
</br>

<div class="admin_users index">
    
    <h2>Admin Users</h2>
    <%= link_to("Add New Admin", new_admin_user_path, :class => 'action new') %>
    <div><%= pluralize(@admin_list.size, 'admin user') %> found</div>
    <table class="listing" summary="Admin list">
        <tr class="header">
            <th>Username</th>
            <th>Name</th>
            <th>Email</th>
            <th>Created</th>
        </tr>
        <% @admin_list.each do |admin| %>
        <tr>
            <td><%= admin.username %></td>
            <td><%= admin.name %></td>
            <td><%= admin.email %></td>
            <td><%= admin.created_at %></td>
            <td class="actions">
                <%= link_to("Edit", edit_admin_user_path(admin), :class => 'action edit') %>
                <%= link_to("Delete", delete_admin_user_path(admin), :class => 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "New Admin User" %>

<%= link_to("<< Back to Admin List", admin_users_path, :class => 'back-link') %>

    <div class="admin-users new">
        <h2>Create Admin User</h2>
        
        <%= form_for @admin do |f| %>
            
            <%= render(:partial => 'form', :locals => {:f => f}) %>
            
            <div class="form-buttons">
                <%= f.submit("Create Admin User") %>
            </div>
        <% end %>
    </div>